// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZRN6VmbUDLqJ5ei66lLcJpBdku5XlS0w',
    appId: '1:707194801773:web:cb3d57a78799a20e88b964',
    messagingSenderId: '707194801773',
    projectId: 'mockathon-dc9a3',
    authDomain: 'mockathon-dc9a3.firebaseapp.com',
    storageBucket: 'mockathon-dc9a3.firebasestorage.app',
    measurementId: 'G-MH29NGZBQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuNzcdyBmQO-S83Ke4kqoTtHd7sO503Gs',
    appId: '1:707194801773:android:358fd2770e97921288b964',
    messagingSenderId: '707194801773',
    projectId: 'mockathon-dc9a3',
    storageBucket: 'mockathon-dc9a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_n7x-f79bChnG31lK_YutkHQ9xDTo0c',
    appId: '1:707194801773:ios:2d2d51b469af480888b964',
    messagingSenderId: '707194801773',
    projectId: 'mockathon-dc9a3',
    storageBucket: 'mockathon-dc9a3.firebasestorage.app',
    iosBundleId: 'com.example.mockathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY_n7x-f79bChnG31lK_YutkHQ9xDTo0c',
    appId: '1:707194801773:ios:2d2d51b469af480888b964',
    messagingSenderId: '707194801773',
    projectId: 'mockathon-dc9a3',
    storageBucket: 'mockathon-dc9a3.firebasestorage.app',
    iosBundleId: 'com.example.mockathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZRN6VmbUDLqJ5ei66lLcJpBdku5XlS0w',
    appId: '1:707194801773:web:ea4e258e8095e86088b964',
    messagingSenderId: '707194801773',
    projectId: 'mockathon-dc9a3',
    authDomain: 'mockathon-dc9a3.firebaseapp.com',
    storageBucket: 'mockathon-dc9a3.firebasestorage.app',
    measurementId: 'G-8710ZK8WWS',
  );
}
